import { describe, expect, it } from 'vitest';
import { executeTool, initialScene } from './scene';
describe('geometry and tool validation', () => {
  it('reads a detached snapshot with coordinate conventions', () => { const s = initialScene(); const r = executeTool(s,'get_scene',{}); s[0].x=99; expect((r.shapes as typeof s)[0].x).toBe(120); expect(r.board).toMatchObject({origin:'top-left'}); });
  it('moves to a centre and verifies full containment', () => { const s=initialScene(); expect(executeTool(s,'move_shape',{shape_id:'red_circle',x:440,y:220}).ok).toBe(true); expect(executeTool(s,'check_relation',{subject_id:'red_circle',relation:'inside',target_id:'green_rectangle'}).result).toBe(true); s[0].x=335; expect(executeTool(s,'check_relation',{subject_id:'red_circle',relation:'inside',target_id:'green_rectangle'}).result).toBe(false); s[0].x=358; expect(executeTool(s,'check_relation',{subject_id:'red_circle',relation:'inside',target_id:'green_rectangle'}).result).toBe(true); });
  it.each([[-1,40],[20,40],[700,40],[40,410],[NaN,40],[Infinity,40],['40',40]])('rejects invalid move %s %s', (x,y) => { const s=initialScene(), before=structuredClone(s); expect(executeTool(s,'move_shape',{shape_id:'red_circle',x,y}).ok).toBe(false); expect(s).toEqual(before); });
  it('accepts exact board boundaries', () => {const s=initialScene(); expect(executeTool(s,'move_shape',{shape_id:'red_circle',x:28,y:392}).ok).toBe(true);});
  it('rejects fixed, missing, unknown tools and unsupported relations', () => {const s=initialScene(); for(const [n,a] of [['move_shape',{shape_id:'green_rectangle',x:100,y:100}],['move_shape',{shape_id:'missing',x:100,y:100}],['delete_everything',{}],['check_relation',{subject_id:'red_circle',target_id:'missing',relation:'inside'}],['check_relation',{subject_id:'red_circle',target_id:'blue_square',relation:'near'}]] as const) expect(executeTool(s,n,a).ok).toBe(false);});
  it.each(['left_of','right_of','above','below'])('checks full extent for %s', relation => {const s=initialScene(); s[0].x=180;s[0].y=300; expect(executeTool(s,'check_relation',{subject_id:'red_circle',target_id:'blue_square',relation}).result).toBe(false); if(relation==='left_of')s[0].x=120;if(relation==='right_of')s[0].x=240;if(relation==='above')s[0].y=240;if(relation==='below')s[0].y=360; expect(executeTool(s,'check_relation',{subject_id:'red_circle',target_id:'blue_square',relation}).result).toBe(true);});
});
